### ISSUE TITLE
GraphQL Schema Error

### ISSUE THREAD

**Issue by codeocelot** [COVID19Tracking/covid-tracking-api#36]
Hi 👋

I think a recent change to the graphql schema broke the api.  If you fetch the graphql endpoint, the following error is returned:

```
Error: Interface field DataPoint.positives expected but USDailyDataPoint does not provide it.

Interface field DataPoint.negatives expected but USDailyDataPoint does not provide it.

Interface field DataPoint.positivesPlusNegatives expected but USDailyDataPoint does not provide it.

Interface field DataPoint.deaths expected but USDailyDataPoint does not provide it.
    at m (worker.js:29:129250)
    at x (worker.js:29:6581)
    at E (worker.js:29:5626)
    at Module.O (worker.js:29:5365)
    at Object.t.generateSchemaHash (worker.js:51:56541)
    at l.generateSchemaDerivedData (worker.js:51:147)
    at new t.ApolloServerBase (worker.js:39:274246)
    at new l (worker.js:73:19678)
    at worker.js:39:128673
    at a (worker.js:39:128736)
```

**Comment by Nosferican** [comment]
Still broken more than three weeks after.
Related https://github.com/COVID19Tracking/issues/issues/186
